Search page
Mau-MD/conecta-digeek-2024 pull request #1
Opened 2024-05-06 20:27 UTC by Clanie1

# Pagina de Busqueda de Blogs junto con vista provisional de Blog

<img width="1502" alt="image" src="https://github.com/Mau-MD/conecta-digeek-2024/assets/79416917/c939df48-c19d-423f-846c-6a62207b0f9a">
<img width="1502" alt="image" src="https://github.com/Mau-MD/conecta-digeek-2024/assets/79416917/45772aab-0202-4dd6-95cd-34d13898f084">

Quedan detalles por corregir en la ventana de Blog ya que la respuesta de la api tuvo modificaciones al momento de implementar la tabla de tags.

La ventana de Search implementa:
- fetch de blogs
- fetch de tags
- filtro de blogs por fecha y tags

La vista arroja un numero de errores por los url's de imagen guardados en db.

> La busqueda por searchbar queda incompleta hasta discutir el algoritmo de busqueda

2024-05-06 22:33 UTC, Mau-MD requested changes

2024-05-06 22:33 UTC, Mau-MD commented on frontend/src/components/search/SearchList.jsx
> +  const [vlogs, setVlogs] = useState([]);
blogs*

2024-05-06 22:33 UTC, Mau-MD commented on frontend/src/components/search/SearchList.jsx
> +  console.log(vlogs);
remove console.log

2024-05-06 22:33 UTC, Mau-MD commented on frontend/src/components/search/SearchList.jsx
> +  };
tienes que wrappear `getBlogs` en un `useCallback` o cada vez que se renderize el componente, se recreará la función. Las dependencias en este caso sería `setFilteredBlogs` y `setBlogs`

2024-05-06 22:33 UTC, Mau-MD commented on frontend/src/components/search/SearchList.jsx
> +  const [vlogs, setVlogs] = useState([]);
initialBlogs*

2024-05-06 22:33 UTC, Mau-MD commented on frontend/src/components/search/SearchList.jsx
> +      const res = await fetch("https://rickandmortyapi.com/api/character");
Por qué no estas usando la API de solis?

2024-05-06 22:33 UTC, Mau-MD commented on frontend/src/components/search/SearchList.jsx
> +          />
Deberías usar un form y un form submit para evitar hacer onKeyDown, pero está bien

2024-05-06 22:33 UTC, Mau-MD commented on frontend/src/components/search/SearchList.jsx
> +            return <VlogCard key={index} vlog={vlog} />;
no uses index como key, debería ser `blog.id`

2024-05-06 22:33 UTC, Mau-MD commented on frontend/src/components/search/VlogCard.jsx
> +    alert("Redirecting to vlog");
alert?

2024-05-06 22:33 UTC, Mau-MD commented on frontend/src/components/search/VlogCard.jsx
> +          <label className="sm text-slate-600">Carlos Aleman</label>
Se te olvido utilizar blog.author

2024-05-06 22:33 UTC, Mau-MD commented on frontend/src/components/search/VlogCard.jsx
> +          </button>
Quitar likes

2024-05-06 22:33 UTC, Mau-MD commented on frontend/src/components/search/VlogCard.jsx
> +          <label>{vlog.id}</label>
Para qué el label?

2024-05-07 15:11 UTC, Mau-MD requested changes
El filtro lo estás haciendo mal, debería ser un `and` con todos los parámetros.

El filtro debería ser una sola funcion que englobe tags, autores, fechas, etc.

Así te aseguras que siempre sea un and

2024-05-07 15:11 UTC, Mau-MD commented on frontend/src/components/Blog.jsx
> +  };
useCallback con dependencia a `setBlog`

2024-05-07 15:11 UTC, Mau-MD commented on frontend/src/components/Blog.jsx
> +
Hazlo componente y usalo en todas las instancias donde haya un Server Component

2024-05-07 15:11 UTC, Mau-MD commented on frontend/src/components/search/BlogCard.jsx
> +  };
useCallback sin ninguna dependencia.

No necesitas el evento

2024-05-07 15:11 UTC, Mau-MD commented on frontend/src/components/search/SearchList.jsx
> +
Todas las funciones deberían de tener useCallback

2024-05-07 15:11 UTC, Mau-MD commented on frontend/src/components/search/SearchList.jsx
> +    const posts = await getPosts(selectedTags.map((tag) => tag.id));
Solo se filtra por tags?

2024-05-07 15:11 UTC, Mau-MD commented on frontend/src/components/search/SearchList.jsx
> +    const posts = await getPosts(selectedTags.map((tag) => tag.id));
Por qué en tu primer fetch de blogs ya estás filtrando por selectedTags, no deberias de siempre tener la lista base (sin filtros) aquí?

2024-05-07 15:11 UTC, Mau-MD commented on frontend/src/components/search/SearchList.jsx
> +    const posts = await getPosts(selectedTags.map((tag) => tag.id));
Ya vi que se fetchea muchas veces, estas reemplazando tus blogs iniciales y estas rompiendo los filtros

2024-05-07 15:11 UTC, Mau-MD commented on frontend/src/components/search/SearchList.jsx
> +  }, [selectedTags]);
Esta la posibilidad que los blogs se fetcheen antes de que fetchees los server tags. deberias asegurarte que están definidos 

`[selectedTags]` se va a llamar tambien en el primer render de la página

2024-05-09 18:30 UTC, Clanie1 commented on frontend/src/components/search/SearchList.jsx
> +  }, [selectedTags]);
Deberia eleminar mi segundo useEffect y hacer una funcion para filtrar y llamarla cada que se hace un cambio en los selectedTags y en la fecha o hay alguna manera de implementarlo con useEffect sin rederizar extra?

2024-05-09 18:31 UTC, Clanie1 commented on frontend/src/components/Blog.jsx
> +  };
Por que dependencia a setBlogs y no dependencia vacia?

2024-05-10 00:22 UTC, Mau-MD commented on frontend/src/components/search/SearchList.jsx
> +  }, [selectedTags]);
Crea un solo useEffect con dependencia de `selectedTags`, `selectedAuthor`, `searchQuery`, etc. Ahí mismo ya mandas a llamar `getBlogs` y les mandas todos los parámetros que quieras filtrar

2024-05-10 00:22 UTC, Mau-MD commented on frontend/src/components/search/SearchList.jsx
> +  }, [selectedTags]);
También asegura que los `serverTags` están definidos desde antes de hacer algun fetch de filtro

2024-05-10 00:23 UTC, Mau-MD commented on frontend/src/components/Blog.jsx
> +  };
De hecho, my bad, la dependencia debería ser `blogId`, al función se debe de rehacer cada vez que `blogId` cambie

2024-05-16 23:31 UTC, Mau-MD approved these changes

2024-05-16 23:31 UTC, Mau-MD commented on frontend/src/components/search/SearchList.jsx
> +    getBlogs(filters);
Estas fetcheando las tagas cada vez que selectedTags cambian, un chorro de llamadsa al servidor

2024-05-16 23:31 UTC, Mau-MD commented on frontend/src/components/search/SearchList.jsx
> +  }, [searchQuery]);
deberias de filtrar desde los blogs iniciales, no desde filteredBlogs, lo que estas haciendo aqui es que cada vez que filtres reduces el tamano de filteredBlogs

2024-05-16 23:31 UTC, merged